backend:
  name: github
  repo: Turutupa/alblog
  branch: main

media_folder: content/assets
public_folder: ../assets

collections:
  - name: my-thoughts
    label: My Thoughts
    folder: content/blog
    create: true
    fields:
      - { name: 'title', label: 'Title' }
      - { name: 'date', label: 'Date', widget: 'date' }
      - { name: 'category', label: 'Category', default: 'random' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
